### ISSUE TITLE
DDMMSS.SSSSが変換できません

### ISSUE THREAD

**Issue by wata909** [geolonia/normalize-any-latlng#2]
Geolonia Mapsで試しましたが、

北緯360613.58925　東経1400516.27815

を試したところ、ロッキー山脈の山の中に飛ばされてしまいました。

フォーマットとしては、「度分秒.秒」という形になっていて、ちょっと変則的です。
実は、地理院さんの平面直角座標への換算サイトの入力がこうなっているのですよね・・・（汗
https://vldb.gsi.go.jp/sokuchi/surveycalc/surveycalc/bl2xyf.html

あまり使う場合はないかもしれませんが、参考までに。

**Comment by wata909** [comment]
なお、これはさすがに無理ゲーだと思うのですが、DD.MMSSSSと、DD.DDDDDの判断ってつくでしょうか（汗

**Comment by kamataryo** [comment]
@wata909 試していただきありがとうございます！

### 1. 「度分秒.秒」 型について

こちら、 `北緯360613.58925　東経1400516.27815` を入力して試したところ、以下のように出力されました。東西方向に地球を n 週してこの結果になったようです。

```json
{ "lat": null, "lng": 116.27814999991097 }
```

https://maps.geolonia.com の検索テキストボックスでは、緯度経度の両方の値が正規化されなければただの名前検索になるので、この結果になったと思われます..

次の _2._ とも関係しますが、 緯度が 0°1'0"（= `000100.00`）未満の時に 10進表示と区別がつかなくなるのでちょっと悩ましいですね..

ただ、0°1'0" 以上の時は10進数表示でないことは明らかなので、このフォーマットへの対応を試してみたいと思います！

### 2. 「DD.MMSSSS」と「DD.DDDDD」について

こちらは、ちょっと考えていまして、完全な区別は難しいとしても、それぞれのパターンで正規化した両方の結果とそれに合わせて `Relevance` の値を返すようなインターフェースがあれば、便利なユースケースもあるかもしれないと考えています。
サービスに組み込むことを考えた場合、複数の選択肢があっても逆ジオコーディングできれば、ユーザーさんに絞ってもらうことができそうです。

**Comment by kamataryo** [comment]
こちら、対応してみました！
<img width="1440" alt="スクリーンショット 2023-09-05 14 28 03" src="https://github.com/geolonia/normalize-any-latlng/assets/6292312/503a654a-9ee4-48e6-b64a-377fae56bbab">

**Comment by wata909** [comment]
素晴らしい！　ありがとうございます！

**Comment by kamataryo** [comment]
2. の方についても、インターフェースの設計や事例を集めていきたいと思います！
